---
# cloud_controller_uri: api.vcap.me
service:
  name: elasticsearch
  version: "1.7.1"
  description: 'Elasticsearch text search service'
  plans: ['free']
  default_plan: free
  tags: ['elasticsearch', 'elasticsearch-1.7.1', 'search']
  timeout: 20
ip_route: localhost
index: 0
token: "0xdeadbeef"
logging:
  level: debug
mbus: nats://localhost:4222
pid: /var/vcap/sys/run/elasticsearch_service.pid
node_timeout: 20
# z_interval: 30
# check_orphan_interval: 3600
# double_check_orphan_interval: 300
